# -*- coding: utf-8 -*-
"""Copy of pipefinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lQ_tTDEsrb98qzUkrTfJQsH2n_9HnY1u
"""

!pip install -q gcsfs

from google.colab import drive
drive.mount('/content/drive')

import google.colab.auth
google.colab.auth.authenticate_user()

!gsutil cp gs://ransmap-bucket/models/lgbm_ransom_detector.txt /content/

!ls /content/

import lightgbm as lgb

MODEL_PATH = "/content/lgbm_ransom_detector.txt"

lgb_model = lgb.Booster(model_file=MODEL_PATH)

print("LightGBM model loaded successfully")

import pandas as pd

FEATURE_FILE = "/content/ata_write_test_features.csv"

features_df = pd.read_csv(FEATURE_FILE)

print("Shape:", features_df.shape)

display(features_df.head())

import pandas as pd
import lightgbm as lgb
import numpy as np

# ============================================================
# STEP 1: PATHS
# ============================================================

FEATURE_FILE = "/content/zipc.csv"

MODEL_PATH = "/content/lgbm_ransom_detector.txt"

OUTPUT_FILE = "/content/ata_write_test_classification.csv"


# ============================================================
# STEP 2: LOAD FEATURE FILE
# ============================================================

features_df = pd.read_csv(FEATURE_FILE)

print("Loaded feature shape:", features_df.shape)


# ============================================================
# STEP 3: LOAD LIGHTGBM MODEL (from bucket copied locally)
# ============================================================

lgb_model = lgb.Booster(
    model_file=MODEL_PATH
)

trained_features = lgb_model.feature_name()

print("Model expects:", trained_features)


# ============================================================
# STEP 4: ALIGN FEATURES CORRECTLY (THIS FIXES YOUR ERROR)
# ============================================================

# Create copy
X_lgb = features_df.copy()

# Add missing columns
for col in trained_features:

    if col not in X_lgb.columns:
        X_lgb[col] = 0


# Keep only required columns and correct order
X_lgb = X_lgb[trained_features]


print("Final input shape:", X_lgb.shape)


# ============================================================
# STEP 5: RUN PREDICTION
# ============================================================

window_probs = lgb_model.predict(X_lgb)

print("Prediction successful")


# ============================================================
# STEP 6: CLASSIFY WINDOWS
# ============================================================

LOW_THRESHOLD = 0.35
HIGH_THRESHOLD = 0.98

labels = []

for p in window_probs:

    if p < LOW_THRESHOLD:
        labels.append("BENIGN")

    elif p > HIGH_THRESHOLD:
        labels.append("RANSOMWARE")

    else:
        labels.append("UNCERTAIN")


# ============================================================
# STEP 7: SAVE OUTPUT FILE
# ============================================================

result_df = features_df.copy()

result_df["probability"] = window_probs

result_df["classification"] = labels

result_df.to_csv(OUTPUT_FILE, index=False)


print("\nSaved classification file at:")
print(OUTPUT_FILE)


# Show preview
display(result_df.head())

import pandas as pd

# Path to your output file
OUTPUT_FILE = "/content/ata_write_test_classification.csv"

# Load classification results
df = pd.read_csv(OUTPUT_FILE)

# Count classifications
counts = df["classification"].value_counts()

# Ensure all classes are shown (even if zero)
counts = counts.reindex(
    ["RANSOMWARE", "UNCERTAIN", "BENIGN"],
    fill_value=0
)

print("Window classification counts:")
print(counts)



import pandas as pd
import lightgbm as lgb
import numpy as np

# ============================================================
# STEP 1: PATHS
# ============================================================

FEATURE_FILE = "/content/zipc.csv"

MODEL_PATH = "/content/lgbm_ransomware_model3.txt"

OUTPUT_FILE = "/content/ata_write_test_classification.csv"


# ============================================================
# STEP 2: LOAD FEATURE FILE
# ============================================================

features_df = pd.read_csv(FEATURE_FILE)

print("Loaded feature shape:", features_df.shape)


# ============================================================
# STEP 3: LOAD LIGHTGBM MODEL (from bucket copied locally)
# ============================================================

# Re-copy the model to ensure it's available
!gsutil cp gs://ransmap-bucket/models/lgbm_ransomware_model3.txt {MODEL_PATH}

lgb_model = lgb.Booster(
    model_file=MODEL_PATH
)

trained_features = lgb_model.feature_name()

print("Model expects:", trained_features)


# ============================================================
# STEP 4: ALIGN FEATURES CORRECTLY (THIS FIXES YOUR ERROR)
# ============================================================

# Create copy
X_lgb = features_df.copy()

# Add missing columns
for col in trained_features:

    if col not in X_lgb.columns:
        X_lgb[col] = 0


# Keep only required columns and correct order
X_lgb = X_lgb[trained_features]


print("Final input shape:", X_lgb.shape)


# ============================================================
# STEP 5: RUN PREDICTION
# ============================================================

window_probs = lgb_model.predict(X_lgb)

print("Prediction successful")


# ============================================================
# STEP 6: CLASSIFY WINDOWS
# ============================================================

LOW_THRESHOLD = 0.20
HIGH_THRESHOLD = 0.90

labels = []

for p in window_probs:

    if p < LOW_THRESHOLD:
        labels.append("BENIGN")

    elif p > HIGH_THRESHOLD:
        labels.append("RANSOMWARE")

    else:
        labels.append("UNCERTAIN")


# ============================================================
# STEP 7: SAVE OUTPUT FILE
# ============================================================

result_df = features_df.copy()

result_df["probability"] = window_probs

result_df["classification"] = labels

result_df.to_csv(OUTPUT_FILE, index=False)


print("\nSaved classification file at:")
print(OUTPUT_FILE)


# Show preview
display(result_df.head())

"""lstm"""

import pandas as pd
import numpy as np
import os

# ============================================================
# CONFIGURATION
# ============================================================

MEM_PATH = "/content/mem_write_preprocessed.csv"
ATA_PATH = "/content/ata_write_preprocessed.csv"

OUTPUT_PATH = "/content/combined_events.csv"

RUN_ID = "Firefox-20230428_00-35-50"

print("\n🔥 Generating combined_events.csv with EXACT column order\n")


# ============================================================
# LOAD FILES
# ============================================================

mem = pd.read_csv(MEM_PATH) if os.path.exists(MEM_PATH) else None
ata = pd.read_csv(ATA_PATH) if os.path.exists(ATA_PATH) else None

if mem is None and ata is None:
    raise Exception("No input files found")


# ============================================================
# STANDARDIZE MEM FILE
# ============================================================

if mem is not None:

    mem = mem.copy()

    mem["type"] = np.int8(1)

    mem["source"] = "mem"

    mem["file_id"] = RUN_ID

    mem["LBA"] = np.nan

    if "ignore" not in mem.columns:
        mem["ignore"] = 0


# ============================================================
# STANDARDIZE ATA FILE
# ============================================================

if ata is not None:

    ata = ata.copy()

    ata["type"] = np.int8(2)

    ata["source"] = "disk"

    ata["file_id"] = RUN_ID

    ata["GPA"] = np.nan

    if "ignore" not in ata.columns:
        ata["ignore"] = 0


# ============================================================
# MERGE FILES
# ============================================================

frames = []

if mem is not None:
    frames.append(mem)

if ata is not None:
    frames.append(ata)

merged = pd.concat(frames, ignore_index=True)


# ============================================================
# CREATE TIMESTAMP
# ============================================================

merged["timestamp"] = (
    merged["time_s"].astype(np.int64) * 1_000_000_000 +
    merged["time_ns"].astype(np.int64)
)


# ============================================================
# CREATE RELATIVE TIMESTAMP
# ============================================================

t0 = merged["timestamp"].min()

merged["t_rel"] = merged["timestamp"] - t0


# ============================================================
# SORT BY TIMESTAMP
# ============================================================

merged = merged.sort_values("timestamp").reset_index(drop=True)


# ============================================================
# FORCE EXACT COLUMN ORDER (MATCHES YOUR SCREENSHOT)
# ============================================================

merged = merged[[
    "time_s",
    "time_ns",
    "GPA",
    "size",
    "entropy",
    "type",
    "label",
    "source",
    "file_id",
    "LBA",
    "ignore",
    "timestamp",
    "t_rel"
]]


# ============================================================
# SAVE FILE
# ============================================================

merged.to_csv(
    OUTPUT_PATH,
    index=False
)


# ============================================================
# VERIFY OUTPUT
# ============================================================

print("\n✅ combined_events.csv generated successfully")
print("Saved at:", OUTPUT_PATH)

print("\nCorrect column order:")
for i, col in enumerate(merged.columns):
    print(f"{i+1}. {col}")

print("\nPreview:")
print(merged.head())

import os
import pandas as pd
import numpy as np

# ============================================================
# CONFIGURATION
# ============================================================

INPUT_FILE = "/content/combined_events.csv"
OUTPUT_FILE = "/content/windowed_output/windowed_events.csv"

WINDOW_NS = 100_000_000  # 100 ms

os.makedirs("/content/windowed_output", exist_ok=True)

print("\n🚀 Generating windowed_events.csv in EXACT format\n")


# ============================================================
# LOAD FILE
# ============================================================

df = pd.read_csv(INPUT_FILE)

print("Loaded rows:", len(df))


# ============================================================
# CREATE t_rel IF MISSING
# ============================================================

if "t_rel" not in df.columns:

    df["timestamp"] = (
        df["time_s"].astype(np.int64) * 1_000_000_000 +
        df["time_ns"].astype(np.int64)
    )

    t0 = df["timestamp"].min()

    df["t_rel"] = df["timestamp"] - t0


# ============================================================
# CREATE WINDOW ID
# ============================================================

df["window_id"] = (df["t_rel"] // WINDOW_NS).astype(np.int64)


# ============================================================
# LABEL
# ============================================================

run_label = int(df["label"].iloc[0])


# ============================================================
# MEMORY FEATURES
# ============================================================

mem_df = df[df["source"] == "mem"]

mem_feat = mem_df.groupby("window_id").agg(

    mem_write_count=("source", "count"),
    mem_avg_entropy=("entropy", "mean"),
    mem_std_entropy=("entropy", "std"),
    mem_total_bytes=("size", "sum"),
    mem_gpa_variance=("GPA", "var")

).reset_index()


# ============================================================
# DISK FEATURES
# ============================================================

disk_df = df[df["source"] == "disk"]

disk_feat = disk_df.groupby("window_id").agg(

    disk_write_count=("source", "count"),
    disk_avg_entropy=("entropy", "mean"),
    disk_total_bytes=("size", "sum"),
    disk_lba_variance=("LBA", "var")

).reset_index()


# ============================================================
# MERGE FEATURES
# ============================================================

win_df = pd.merge(
    mem_feat,
    disk_feat,
    on="window_id",
    how="outer"
)


# ============================================================
# FILL MISSING VALUES
# ============================================================

win_df = win_df.fillna(0)


# ============================================================
# ADD TIME FEATURE
# ============================================================

win_df["time_sec"] = win_df["window_id"] * (WINDOW_NS / 1e9)


# ============================================================
# ADD LABEL
# ============================================================

win_df["label"] = run_label


# ============================================================
# EXACT COLUMN ORDER (MATCHES YOUR SCREENSHOT)
# ============================================================

win_df = win_df[[
    "window_id",
    "mem_write_count",
    "mem_avg_entropy",
    "mem_std_entropy",
    "mem_total_bytes",
    "mem_gpa_variance",
    "disk_write_count",
    "disk_avg_entropy",
    "disk_total_bytes",
    "disk_lba_variance",
    "time_sec",
    "label"
]]


# ============================================================
# SORT BY window_id
# ============================================================

win_df = win_df.sort_values("window_id").reset_index(drop=True)


# ============================================================
# SAVE FILE
# ============================================================

win_df.to_csv(
    OUTPUT_FILE,
    index=False
)


# ============================================================
# VERIFY OUTPUT
# ============================================================

print("\n✅ windowed_events.csv generated successfully")
print("Saved at:", OUTPUT_FILE)

print("\nCorrect column order:")
print(list(win_df.columns))

print("\nPreview:")
print(win_df.head())

import numpy as np
import pandas as pd
from tqdm import tqdm

# ============================================================
# CONFIGURATION
# ============================================================

INPUT_FILE = "/content/windowed_output/windowed_events.csv"

SEQUENCE_LENGTH = 50

OUTPUT_FILE = "/content/X_sequences.npy"


# ============================================================
# FAST SCALER (IDENTICAL TO TRAINING PIPELINE)
# ============================================================

class FastScaler:

    def fit_transform(self, X):

        mean = X.mean(axis=0, dtype=np.float32)

        std = X.std(axis=0, dtype=np.float32)

        std[std == 0] = 1e-8

        return ((X - mean) / std).astype(np.float32)


# ============================================================
# LOAD WINDOWED EVENTS FILE
# ============================================================

print("\nLoading windowed_events.csv...")

df = pd.read_csv(INPUT_FILE)

print("Total windows:", len(df))


# ============================================================
# EXACT FEATURE COLUMN ORDER (CRITICAL — MUST MATCH TRAINING)
# ============================================================

FEATURE_COLUMNS = [

    "mem_write_count",
    "mem_avg_entropy",
    "mem_std_entropy",
    "mem_total_bytes",
    "mem_gpa_variance",

    "disk_write_count",
    "disk_avg_entropy",
    "disk_total_bytes",
    "disk_lba_variance",

    "time_sec"
]


# ============================================================
# VERIFY REQUIRED COLUMNS EXIST
# ============================================================

missing = [col for col in FEATURE_COLUMNS if col not in df.columns]

if len(missing) > 0:

    raise Exception(f"Missing columns in windowed_events.csv: {missing}")


# ============================================================
# EXTRACT FEATURES
# ============================================================

X = df[FEATURE_COLUMNS].to_numpy(dtype=np.float32)

print("Feature matrix shape:", X.shape)


# ============================================================
# SCALE FEATURES (IDENTICAL TO TRAINING)
# ============================================================

scaler = FastScaler()

X_scaled = scaler.fit_transform(X)


# ============================================================
# BUILD SEQUENCES (SLIDING WINDOW)
# ============================================================

print("\nBuilding sequences...")

num_windows = X_scaled.shape[0]

X_sequences = []

for i in tqdm(range(num_windows - SEQUENCE_LENGTH + 1)):

    sequence = X_scaled[i : i + SEQUENCE_LENGTH]

    X_sequences.append(sequence)


# ============================================================
# CONVERT TO NUMPY ARRAY (EXACT FORMAT)
# ============================================================

X_sequences = np.array(X_sequences, dtype=np.float32)


# ============================================================
# VERIFY FORMAT
# ============================================================

print("\n===================================")
print("FORMAT VERIFICATION")
print("===================================")

print("Shape:", X_sequences.shape)
print("Dtype:", X_sequences.dtype)

print("\nExpected format:")
print("(num_sequences, 50, 10)")
print("float32")


# ============================================================
# SAVE FILE
# ============================================================

np.save(OUTPUT_FILE, X_sequences)


print("\n✅ X_sequences.npy GENERATED SUCCESSFULLY")
print("Saved at:", OUTPUT_FILE)

!gsutil cp gs://ransmap-bucket/original/i-3\ gen-12/ddr4-2133-16g/final_lstm_model.keras /content/

model = tf.keras.models.load_model("/content/final_lstm_model.keras")

model = tf.keras.models.load_model(MODEL_PATH)

print("Model loaded successfully")
model.summary()

# ============================================================
# LSTM TESTING SCRIPT — BINARY OUTPUT ONLY
# BENIGN or RANSOMWARE
# ============================================================

import numpy as np
import pandas as pd
import tensorflow as tf

# ============================================================
# CONFIGURATION
# ============================================================

MODEL_PATH = "gs://ransmap-bucket/original/i-3 gen-12/ddr4-2133-16g/final_lstm_model.keras"

FEATURE_FILE = "/content/windowed_output/windowed_events.csv"

OUTPUT_FILE = "/content/lstm_window_classification.csv"

SEQUENCE_LENGTH = 50

THRESHOLD = 0.5


# ============================================================
# STEP 1: LOAD MODEL
# ============================================================

print("Loading LSTM model...")

model = tf.keras.models.load_model(MODEL_PATH)

print("Model loaded")


# ============================================================
# STEP 2: LOAD FEATURES
# ============================================================

df = pd.read_csv(FEATURE_FILE)

print("Loaded feature shape:", df.shape)


# ============================================================
# STEP 3: EXACT FEATURE ORDER
# ============================================================

FEATURE_COLUMNS = [

    "mem_write_count",
    "mem_avg_entropy",
    "mem_std_entropy",
    "mem_total_bytes",
    "mem_gpa_variance",

    "disk_write_count",
    "disk_avg_entropy",
    "disk_total_bytes",
    "disk_lba_variance",

    "time_sec"
]

X = df[FEATURE_COLUMNS].values.astype(np.float32)


# ============================================================
# STEP 4: SCALE FEATURES
# ============================================================

mean = X.mean(axis=0, dtype=np.float32)
std = X.std(axis=0, dtype=np.float32)

std[std == 0] = 1e-8

X_scaled = (X - mean) / std


# ============================================================
# STEP 5: BUILD SEQUENCES
# ============================================================

sequences = []

for i in range(len(X_scaled) - SEQUENCE_LENGTH + 1):

    sequences.append(X_scaled[i:i+SEQUENCE_LENGTH])

X_seq = np.array(sequences, dtype=np.float32)

print("Sequence shape:", X_seq.shape)


# ============================================================
# STEP 6: PREDICT
# ============================================================

probs = model.predict(X_seq, verbose=0).flatten()

print("Prediction complete")


# ============================================================
# STEP 7: ALIGN WITH WINDOWS
# ============================================================

padding = [np.nan] * (SEQUENCE_LENGTH - 1)

full_probs = padding + list(probs)


# ============================================================
# STEP 8: BINARY CLASSIFICATION ONLY
# ============================================================

labels = []

for p in full_probs:

    if np.isnan(p):

        labels.append("BENIGN")   # or skip

    elif p >= THRESHOLD:

        labels.append("RANSOMWARE")

    else:

        labels.append("BENIGN")


# ============================================================
# STEP 9: SAVE OUTPUT
# ============================================================

result_df = df.copy()

result_df["probability"] = full_probs

result_df["classification"] = labels

result_df.to_csv(OUTPUT_FILE, index=False)


print("\nSaved:", OUTPUT_FILE)

print("\nPreview:")
print(result_df.head())

import pandas as pd

# ============================================================
# LOAD LSTM OUTPUT FILE
# ============================================================

OUTPUT_FILE = "/content/lstm_window_classification.csv"

df = pd.read_csv(OUTPUT_FILE)

print("Loaded:", OUTPUT_FILE)
print("Total windows:", len(df))


# ============================================================
# COUNT EACH CLASS
# ============================================================

benign_count = (df["classification"] == "BENIGN").sum()

ransomware_count = (df["classification"] == "RANSOMWARE").sum()


# ============================================================
# PRINT RESULTS
# ============================================================

print("\n====================================")
print("LSTM CLASSIFICATION SUMMARY")
print("====================================")

print("BENIGN windows     :", benign_count)
print("RANSOMWARE windows :", ransomware_count)

print("TOTAL windows      :", benign_count + ransomware_count)


# ============================================================
# OPTIONAL: SHOW PERCENTAGE
# ============================================================

total = len(df)

print("\nPercentage:")

print("BENIGN      : {:.2f}%".format(100 * benign_count / total))
print("RANSOMWARE  : {:.2f}%".format(100 * ransomware_count / total))

# ============================================================
# LSTM TESTING SCRIPT — BINARY OUTPUT ONLY
# BENIGN or RANSOMWARE
# ============================================================

import numpy as np
import pandas as pd
import tensorflow as tf

# ============================================================
# CONFIGURATION
# ============================================================

MODEL_PATH = "gs://ransmap-bucket/original/i-3 gen-12/ddr4-2133-16g/final_lstm_model.keras"
FEATURE_FILE = "gs://ransmap-bucket/original/i-3 gen-12/ddr4-2133-16g/LockBit/LockBit-20230517_21-35-46/windowed_events.csv"
OUTPUT_FILE = "gs://ransmap-bucket/original/i-3 gen-12/ddr4-2133-16g/lstm_window_classification.csv"
SEQUENCE_LENGTH = 50
THRESHOLD = 0.5
TRAIN_MEAN_PATH = "gs://ransmap-bucket/original/i-3 gen-12/ddr4-2133-16g/train_mean.npy"
TRAIN_STD_PATH  = "gs://ransmap-bucket/original/i-3 gen-12/ddr4-2133-16g/train_std.npy"

# ============================================================
# STEP 1: LOAD MODEL
# ============================================================

print("Loading LSTM model...")
model = tf.keras.models.load_model(MODEL_PATH)
print("Model loaded")

# ============================================================
# STEP 2: LOAD TRAINING SCALER FROM GCS
# ============================================================

print("Loading training mean/std for scaling...")

# Use tf.io.gfile.GFile to read npy from GCS
with tf.io.gfile.GFile(TRAIN_MEAN_PATH, 'rb') as f:
    train_mean = np.load(f)
with tf.io.gfile.GFile(TRAIN_STD_PATH, 'rb') as f:
    train_std = np.load(f)

train_std[train_std == 0] = 1e-8  # avoid division by zero
print("Scaler loaded")

# ============================================================
# STEP 3: LOAD FEATURES
# ============================================================

df = pd.read_csv(FEATURE_FILE)
print("Loaded feature shape:", df.shape)

# ============================================================
# STEP 4: EXACT FEATURE ORDER
# ============================================================

FEATURE_COLUMNS = [
    "mem_write_count",
    "mem_avg_entropy",
    "mem_std_entropy",
    "mem_total_bytes",
    "mem_gpa_variance",
    "disk_write_count",
    "disk_avg_entropy",
    "disk_total_bytes",
    "disk_lba_variance",
    "time_sec"
]

X = df[FEATURE_COLUMNS].values.astype(np.float32)

# ============================================================
# STEP 5: SCALE FEATURES USING TRAINING STATS
# ============================================================

X_scaled = (X - train_mean) / train_std

# ============================================================
# STEP 6: BUILD SEQUENCES
# ============================================================

sequences = []
for i in range(len(X_scaled) - SEQUENCE_LENGTH + 1):
    sequences.append(X_scaled[i:i+SEQUENCE_LENGTH])

X_seq = np.array(sequences, dtype=np.float32)
print("Sequence shape:", X_seq.shape)

# ============================================================
# STEP 7: PREDICT
# ============================================================

probs = model.predict(X_seq, verbose=0).flatten()
print("Prediction complete")

# ============================================================
# STEP 8: ALIGN WITH WINDOWS
# ============================================================

padding = [np.nan] * (SEQUENCE_LENGTH - 1)
full_probs = padding + list(probs)

# ============================================================
# STEP 9: BINARY CLASSIFICATION ONLY
# ============================================================

labels = []
for p in full_probs:
    if np.isnan(p):
        labels.append("BENIGN")   # or skip
    elif p >= THRESHOLD:
        labels.append("RANSOMWARE")
    else:
        labels.append("BENIGN")

# ============================================================
# STEP 10: SAVE OUTPUT
# ============================================================

result_df = df.copy()
result_df["probability"] = full_probs
result_df["classification"] = labels

result_df.to_csv(OUTPUT_FILE, index=False)

print("\nSaved:", OUTPUT_FILE)
print("\nPreview:")
print(result_df.head())